### ISSUE TITLE
running kmeans code meet some error? could you give me some advice, thanks

### ISSUE THREAD

**Issue by brucetiancai** [damiangilgonzalez1995/Clustering-with-LLM#1]
1. running code : columns = pipe_fit.get_feature_names_out().tolist()  

error log:

AttributeError: Estimator encoder does not provide get_feature_names_out. Did you mean to call pipeline[:-1].get_feature_names_out()?

2. running code :  visualizer.fit(data_no_outliers)# Fit the data to the visualizer

error log:

TypeError: '<=' not supported between instances of 'str' and 'int'

**Comment by damiangilgonzalez1995** [comment]
Hello,

Let's see if I could give you a hand.

To better understand what is happening, I would need to know which notebook is the one that is giving you problems.

### **Problem: running code : columns = pipe_fit.get_feature_names_out().tolist()**

I just ran the "kmenas" notebook and it works correctly for me. What occurs to me that may be happening is that you are using different versions of the libraries used in this project. Therefore, attach the requirement.txt file.

It would also be nice to be able to see the following values:

- pipe_fit
- pipe_fit.transform(df).shape

###  **Problem: running code : visualizer.fit(data_no_outliers) Fit the data to the visualizer**

Unfortunately, again, I'm not getting the same error as you. It occurs to me that some of the columns are not of type int in the dataset. Please check that all columns in the dataset are of type int.

It would also be nice to be able to see the following values:

- data_no_outliers.dtypes
